remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Quantentheorie ohne Prozess Typ 2
description: Die Lösung des Messproblems der Quantenmechanik durch die Unterscheidung in echte/psychische und scheinbare/physikalische Zeiten
show_downloads: true
